version: '3.8'
name: cpcds-client-ri
services:
  web:
    build: .
    depends_on:
      - cache
    ports:
      - "3000:3000"
    environment:
      - MEMCACHE_SERVERS=cache:11211

  cache:
    image: memcached:alpine
    